### PR TITLE
feat: JSON config helpers

### PR DESCRIPTION
**Pull request by LittleBigBug**
Adds a helper tool to automatically generate config files & de-serialize the JSON to a class for easy use

### CODE REVIEW

**Review by 1zc — COMMENTED** [review]
Sorry for the delay, been away for a bit (still technically am but we ball)

This is pretty cool! However I'm wondering if we should instead go with CounterStrikeSharp's now built-in plugin configuration interface: https://docs.cssharp.dev/examples/WithConfig.html

What do you think? I think this might be a better way to go, so we can stay closer to stock CSSharp functionality

**Comment by LittleBigBug** [comment]
> Sorry for the delay, been away for a bit (still technically am but we ball)
> 
> This is pretty cool! However I'm wondering if we should instead go with CounterStrikeSharp's now built-in plugin configuration interface: https://docs.cssharp.dev/examples/WithConfig.html
> 
> What do you think? I think this might be a better way to go, so we can stay closer to stock CSSharp functionality

No worries! Thanks for taking a look!

I saw that CSSharp had that only right a bit after i submitted this PR! 
I guess my only concern with their cfg interface is it doesn't seem to support multiple configs. So if you don't care all of it being in the same config then I could do that.

Maybe I can PR to CSSharp to provide that functionality if that's preferred

**Comment by tslashd** [comment]
Having all configurations for the Timer in the same `*.json` (excluding `server_settings.cfg`) would definitely in my opinion make it a bit easier to set up. 
We already discussed this in the Discord _(a little bit)_ but currently this PR does not connect to database, data from `database.json` is not being loaded correctly (there was only naming convention conflicts with PR #6). 
Could mark it as **Draft** and just push the CSSharp config functionality whenever if @1zc is okay with that :)

**Review by tslashd — COMMENTED** [review]
Having all configurations for the Timer in the same `*.json` (excluding `server_settings.cfg`) would definitely in my opinion make it a bit easier to set up. 
We already discussed this in the Discord _(a little bit)_ but currently this PR does not connect to database, data from `database.json` is not being loaded correctly (there was only naming convention conflicts with PR #6). 
Could mark it as **Draft** and just push the CSSharp config functionality whenever if @1zc is okay with that :)

**Comment by 1zc** [comment]
I'm happy for it to all be in a single config file! I agree with @tslashd, keeps things simple for the user

**Comment by tslashd** [comment]
Any news on this?

**Pull request closed without merging**
